//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Firm.Model
{
    [Dapper.Contrib.Extensions.Table("D_Admin_Login_Errors")]
    public partial class D_Admin_Login_Errors
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_A_E_Id { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_A_E_Name { get; set; }

        [StringLength(50)]
        public string F_A_E_Pass { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_A_E_IP { get; set; }

        [StringLength(150)]
        public string F_A_E_UserAgent { get; set; }

        [StringLength(150)]
        public string F_A_E_Message { get; set; }

    	[Required]
        public System.DateTime F_A_E_Create { get; set; }
    	
    	}
    
}
