//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Firm.Model
{
    [Dapper.Contrib.Extensions.Table("D_Ad")]
    public partial class D_Ad
    {
        public D_Ad()
        {
            this.D_Ad_To_View = new List<D_Ad_To_View>();
    		var type = typeof(D_Ad);
    		var method = type.GetMethod("PartialStructure", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
            if (method != null)
            {
                method.Invoke(this, null);
            }
        }
    

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_Ad_Id { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_Ad_Title { get; set; }

    	[Required]
        public int F_Ad_Type { get; set; }

    	[Required]
        [StringLength(300)]
        public string F_Ad_Link { get; set; }

        [StringLength(500)]
        public string F_Ad_Image { get; set; }

        [StringLength(500)]
        public string F_Ad_Desc { get; set; }

        public string F_Ad_Html { get; set; }

    	[Required]
        public bool F_Ad_IsLock { get; set; }

    	[Required]
        public System.DateTime F_Ad_Create { get; set; }
    	
    	
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual IList<D_Ad_To_View> D_Ad_To_View { get; set; }
    }
    
}
