//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Firm.Model
{
    [Dapper.Contrib.Extensions.Table("D_Admin_Record")]
    public partial class D_Admin_Record
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_A_Record_Id { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_A_Record_Type { get; set; }

    	[Required]
        public string F_A_Record_OldContent { get; set; }

    	[Required]
        public string F_A_Record_NewContent { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_A_Record_TableName { get; set; }

        public Nullable<int> F_A_Record_AdminId { get; set; }

    	[Required]
        public System.DateTime F_A_Record_Create { get; set; }
    	
    	
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual D_Admin D_Admin { get; set; }
    }
    
}
