//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Firm.Model
{
    [Dapper.Contrib.Extensions.Table("D_Admin_Logs")]
    public partial class D_Admin_Logs
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_A_Log_Admin_Id { get; set; }

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public System.DateTime F_A_Log_Create { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_A_Log_IP { get; set; }

        [StringLength(150)]
        public string F_A_Log_UserAgent { get; set; }
    	
    	
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual D_Admin D_Admin { get; set; }
    }
    
}
