//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Firm.Model
{
    [Dapper.Contrib.Extensions.Table("D_Admin")]
    public partial class D_Admin
    {
        public D_Admin()
        {
            this.D_Admin_Role = new List<D_Admin_Role>();
            this.D_Admin_Logs = new List<D_Admin_Logs>();
            this.D_Admin_Record = new List<D_Admin_Record>();
    		var type = typeof(D_Admin);
    		var method = type.GetMethod("PartialStructure", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
            if (method != null)
            {
                method.Invoke(this, null);
            }
        }
    

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_Admin_Id { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_Admin_Name { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_Admin_Nick { get; set; }

    	[Required]
        [StringLength(32)]
        public string F_Admin_Password { get; set; }

    	[Required]
        public System.DateTime F_Admin_Time_Last { get; set; }

    	[Required]
        public System.DateTime F_Admin_Time_Create { get; set; }

    	[Required]
        public bool F_Admin_IsLock { get; set; }

    	[Required]
        public bool F_Admin_IsSupper { get; set; }
    	
    	
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual IList<D_Admin_Role> D_Admin_Role { get; set; }
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual IList<D_Admin_Logs> D_Admin_Logs { get; set; }
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual IList<D_Admin_Record> D_Admin_Record { get; set; }
    }
    
}
