//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace Firm.Model
{
    [Dapper.Contrib.Extensions.Table("D_Movie_Set")]
    public partial class D_Movie_Set
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_M_S_Movie_Id { get; set; }

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_M_S_Size { get; set; }

    	[Required]
        [StringLength(500)]
        public string F_M_S_Link { get; set; }

    	[Required]
        public int F_M_S_Click { get; set; }
    	
    	
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual D_Movie D_Movie { get; set; }
    }
    
}
