//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Firm.Model
{
    [Dapper.Contrib.Extensions.Table("D_SEO")]
    public partial class D_SEO
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_SEO_Id { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_SEO_Name { get; set; }

        [StringLength(150)]
        public string F_SEO_Title { get; set; }

        [StringLength(500)]
        public string F_SEO_MetaKey { get; set; }

        [StringLength(500)]
        public string F_SEO_MetaContent { get; set; }

        [StringLength(500)]
        public string F_SEO_Link { get; set; }

    	[Required]
        public bool F_SEO_IsLock { get; set; }
    	
    	}
    
}
