//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Admin.Model
{
    [Serializable]
    [Dapper.Contrib.Extensions.Table("T_Admin_Role")]
    public partial class T_Admin_Role
    {
    	
        public T_Admin_Role()
        {
            this.T_Admin_Role_Right = new List<T_Admin_Role_Right>();
            this.T_Admin = new List<T_Admin>();
    		var type = typeof(T_Admin_Role);
    		var method = type.GetMethod("PartialStructure", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
            if (method != null)
            {
                method.Invoke(this, null);
            }
        }
    

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_Role_Id { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_Role_Name { get; set; }

        [StringLength(200)]
        public string F_Role_Description { get; set; }

    	[Required]
        public System.DateTime F_Role_Create { get; set; }

    	[Required]
        public bool F_Role_IsLock { get; set; }
    	
    	
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual IList<T_Admin_Role_Right> T_Admin_Role_Right { get; set; }
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual IList<T_Admin> T_Admin { get; set; }
    }
    
}
