//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Admin.Model
{
    [Serializable]
    [Dapper.Contrib.Extensions.Table("T_Admin_Log")]
    public partial class T_Admin_Log
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_A_L_AdminId { get; set; }

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public System.DateTime F_A_L_LoginTime { get; set; }

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        [StringLength(50)]
        public string F_A_L_Ip { get; set; }
    	
    	
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual T_Admin T_Admin { get; set; }
    }
    
}
