//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Admin.Model
{
    [Serializable]
    [Dapper.Contrib.Extensions.Table("T_AD")]
    public partial class T_AD
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_Ad_Id { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_Ad_Title { get; set; }

    	[Required]
        public int F_Ad_Type { get; set; }

        [StringLength(500)]
        public string F_Ad_Link { get; set; }

        [StringLength(500)]
        public string F_Ad_Image { get; set; }

        [StringLength(500)]
        public string F_Ad_Des { get; set; }

        public string F_Ad_Html { get; set; }

    	[Required]
        public bool F_Ad_IsLock { get; set; }

    	[Required]
        public System.DateTime F_Ad_Create { get; set; }
    	
    	}
    
}
