//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Admin.Model
{
    [Serializable]
    [Dapper.Contrib.Extensions.Table("T_Admin_Role_Right")]
    public partial class T_Admin_Role_Right
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_Admin_Right_RoleId { get; set; }

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        [StringLength(50)]
        public string F_Admin_Right_Controller { get; set; }

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        [StringLength(50)]
        public string F_Admin_Right_Action { get; set; }
    	
    	
    [Dapper.Contrib.Extensions.Write(false)]
    [NotMapped]
        public virtual T_Admin_Role T_Admin_Role { get; set; }
    }
    
}
