//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Admin.Model
{
    [Serializable]
    [Dapper.Contrib.Extensions.Table("T_Image_Record")]
    public partial class T_Image_Record
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_Image_Record_Id { get; set; }

    	[Required]
        [StringLength(500)]
        public string F_Image_Record_FilePath { get; set; }

    	[Required]
        public int F_Image_Record_Num { get; set; }

        public string F_Image_Record_InRecord { get; set; }

    	[Required]
        [StringLength(32)]
        public string F_Image_Record_Md5 { get; set; }
    	
    	}
    
}
