//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Admin.Model
{
    [Serializable]
    [Dapper.Contrib.Extensions.Table("T_Robot")]
    public partial class T_Robot
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_Robot_Id { get; set; }

    	[Required]
        [StringLength(100)]
        public string F_Robot_Name { get; set; }

        [StringLength(50)]
        public string F_Robot_Type { get; set; }

    	[Required]
        [StringLength(500)]
        public string F_Robot_Link { get; set; }

    	[Required]
        public System.DateTime F_Robot_Create { get; set; }

    	[Required]
        public System.DateTime F_Robot_Update { get; set; }

    	[Required]
        public bool F_Robot_IsLock { get; set; }

        [StringLength(500)]
        public string F_Robot_MobileLink { get; set; }
    	
    	}
    
}
