//------------------------------------------------------------------------------
// <auto-generated>
//		自动生成，请勿修改 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
namespace Admin.Model
{
    [Serializable]
    [Dapper.Contrib.Extensions.Table("T_SEO")]
    public partial class T_SEO
    {

    [Dapper.Contrib.Extensions.KeyAttribute]
    	[Required]
        public int F_Seo_Id { get; set; }

    	[Required]
        [StringLength(50)]
        public string F_Seo_Name { get; set; }

    	[Required]
        [StringLength(150)]
        public string F_Seo_MetaKey { get; set; }

    	[Required]
        [StringLength(255)]
        public string F_Seo_MetaContent { get; set; }

    	[Required]
        public System.DateTime F_Seo_Create { get; set; }

    	[Required]
        public System.DateTime F_Seo_Update { get; set; }

    	[Required]
        public bool F_Seo_IsLock { get; set; }

    	[Required]
        [StringLength(100)]
        public string F_Seo_Title { get; set; }

        [StringLength(50)]
        public string F_Seo_Action { get; set; }

        [StringLength(50)]
        public string F_Seo_Controller { get; set; }

    	[Required]
        public int F_Seo_Type { get; set; }

        [StringLength(100)]
        public string F_Seo_Search_Title { get; set; }

        [StringLength(150)]
        public string F_Seo_Search_MetaKey { get; set; }

        [StringLength(255)]
        public string F_Seo_Search_MetaContent { get; set; }

        [StringLength(50)]
        public string F_Seo_Area { get; set; }

        [StringLength(150)]
        public string F_Seo_Link { get; set; }
    	
    	}
    
}
